const router = require("express").Router();
const c = require("../controllers/billingController");
const { authenticate, authorize } = require("../middleware/auth");
router.use(authenticate);
router.get("/", authorize("cashier","manager"), c.getAll);
router.post("/", authorize("cashier","manager"), c.createInvoice);
router.get("/:id", c.getOne);
router.post("/:id/payment", authorize("cashier","manager"), c.recordPayment);
router.get("/customer/:customer_id", c.getByCustomer);
module.exports = router;
