const router = require("express").Router();
const c = require("../controllers/managerController");
const { authenticate, authorize } = require("../middleware/auth");
router.use(authenticate, authorize("manager"));
router.get("/dashboard", c.getDashboard);
router.get("/financial-report", c.getFinancialReport);
router.get("/approvals", c.getPendingApprovals);
router.patch("/approvals/:id/approve", c.approveJob);
router.patch("/approvals/:id/reject", c.rejectJob);
router.get("/staff", c.getAllStaff);
router.post("/staff", c.createStaff);
router.put("/staff/:id", c.updateUser);
router.delete("/staff/:id", c.deleteUser);
router.get("/pending-staff", c.getPendingStaff);
router.patch("/pending-staff/:id/approve", c.approveStaffMember);
router.get("/inventory", c.getInventory);
router.get("/all-jobs", c.getAllJobs);
router.patch("/jobs/:id/status", c.updateJobStatus);
router.get("/requisitions", c.getRequisitions);
router.patch("/requisitions/:id/approve", c.approveRequisition);
router.patch("/requisitions/:id/reject", c.rejectRequisition);
router.get("/services", c.getAllServices);
router.post("/services", c.createService);
router.put("/services/:id", c.updateService);
router.delete("/services/:id", c.deleteService);
module.exports = router;
